name: ✨ Feature request
description: Suggest an idea or enhancement for rn-nitro-screen-recorder
title: "✨ "
labels: [✨ feature]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added and why it would be useful.
      placeholder: I'd like automatic upload of recordings to cloud storage with retry logic because...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed API (optional)
      description: >
        Show how you'd like to use this feature with a code example.
      render: tsx
      placeholder: |
        // Example usage
        const { startRecording } = useGlobalRecording({
          autoUpload: {
            provider: 'aws-s3',
            bucket: 'my-recordings',
            onSuccess: (url) => console.log('Uploaded:', url)
          }
        });
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I searched for similar feature requests and found none
          required: true